/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InternsIndexRouteImport } from './routes/interns/index'
import { Route as InternsInternIdRouteImport } from './routes/interns/$internId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InternsIndexRoute = InternsIndexRouteImport.update({
  id: '/interns/',
  path: '/interns/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternsInternIdRoute = InternsInternIdRouteImport.update({
  id: '/interns/$internId',
  path: '/interns/$internId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/interns/$internId': typeof InternsInternIdRoute
  '/interns/': typeof InternsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/interns/$internId': typeof InternsInternIdRoute
  '/interns': typeof InternsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/interns/$internId': typeof InternsInternIdRoute
  '/interns/': typeof InternsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/follow-ups'
    | '/leads'
    | '/notifications'
    | '/interns/$internId'
    | '/interns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/follow-ups'
    | '/leads'
    | '/notifications'
    | '/interns/$internId'
    | '/interns'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/follow-ups'
    | '/leads'
    | '/notifications'
    | '/interns/$internId'
    | '/interns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  FollowUpsRoute: typeof FollowUpsRoute
  LeadsRoute: typeof LeadsRoute
  NotificationsRoute: typeof NotificationsRoute
  InternsInternIdRoute: typeof InternsInternIdRoute
  InternsIndexRoute: typeof InternsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interns/': {
      id: '/interns/'
      path: '/interns'
      fullPath: '/interns/'
      preLoaderRoute: typeof InternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interns/$internId': {
      id: '/interns/$internId'
      path: '/interns/$internId'
      fullPath: '/interns/$internId'
      preLoaderRoute: typeof InternsInternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  FollowUpsRoute: FollowUpsRoute,
  LeadsRoute: LeadsRoute,
  NotificationsRoute: NotificationsRoute,
  InternsInternIdRoute: InternsInternIdRoute,
  InternsIndexRoute: InternsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
